services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: apartmentrental-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_strong_Passw0rd!"
    ports:
      - "14333:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"Your_strong_Passw0rd!\" -Q \"SELECT 1\" -b -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 25s

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apartmentrental-web
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Docker"
      ConnectionStrings__DefaultConnection: "Server=db;Database=ApartmentRentalDb;User Id=sa;Password=Your_strong_Passw0rd!;TrustServerCertificate=True;"
    ports:
      - "8080:8080"

volumes:
  mssql_data:
